title: "tayoky's website"

author :
  name : "tayoky"
  email : "tayoky4848@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

#use minima theme
remote_theme: "jekyll/minima@e7b6705"

minima:
  skin: auto
  
  nav_pages:
    - about.md
    - project

#social media link
  social_links:
    - title: "tayoky on github"
      icon: github
      url: "https://github.com/tayoky"
